### ISSUE TITLE
error: "Incorrect menuitem class given" - fix available

### ISSUE THREAD

**Issue by RussellEngland** [logicexpertise/totara-local_rbvis#4]
Hey chaps

T12 gives this error:

```
Incorrect menuitem class given. Please provide the full classname including leading backslash, e.g. \totara_core\totara\menu\myreports. Actual value: 'rbvis'
line 1274 of /lib/pagelib.php: call to debugging()
line 20 of /local/rbvis/dashboard.php: call to moodle_page->set_totara_menu_selected()
```
It's because this line:
https://github.com/logicexpertise/totara-local_rbvis/blob/f9949c7aa4021fc56652d01c3598e9cf8bda8184/dashboard.php#L20

Needs to be this:
```
$PAGE->set_totara_menu_selected('\local_rbvis\totara\menu\rbvis');
```

**Comment by logicexpertise** [comment]
Thanks for reporting and providing a fix for this issue, @RussellEngland.
It's been fixed and a new release published.
